server:
  port: 18814

spring:
  datasource:
    username: root
    password: HPyuko12!!
    url: jdbc:mysql://localhost:3306/navigation?useUnicode=true&characterEncoding=utf-8&useSSL=false

jwt:
  accessTokenExpireTime: P30D
  issuer: qdu.life
  refreshTokenExpireAppTime: P30D
  refreshTokenExpireTime: P30D
  secretKey: HP..yuko12!!>>serv


